/** @type {import('react-doctor').Config} */
export default {
  exclude: ["src/extension/**/*", "src/backend/services/**/*", "src/database/**/*", "src/shared/types/**/*"],
  rules: {
    "react-doctor/prefer-module-scope-static-value": "off",
    "react-doctor/no-inline-exhaustive-style": "off",
    "react-doctor/no-multi-comp": "off",
    "react-doctor/prefer-useReducer": "off",
    "react-doctor/no-tiny-text": "off",
    "react-doctor/only-export-components": "off",
    "react-doctor/no-react19-deprecated-apis": "off",
    "react-doctor/no-initialize-state": "off",
    "react-doctor/no-giant-component": "off",
    "react-doctor/no-inline-bounce-easing": "off",
    "react-doctor/no-array-index-as-key": "off",
    "jsx-a11y/anchor-is-valid": "off",
    "unused-export": "off",
    "react-doctor/zod-v4-prefer-top-level-string-formats": "off",
    "react-doctor/no-static-element-interactions": "off",
    "react-doctor/no-large-animated-blur": "off",
    "react-doctor/no-event-handler": "off",
    "react-doctor/nextjs-no-client-side-redirect": "off",
    "jsx-no-duplicate-props": "off",
    "click-events-have-key-events": "off",
    "react-doctor/nextjs-no-a-element": "off",
    "react-doctor/rerender-state-only-in-handlers": "off",
    "react-doctor/rendering-hydration-no-flicker": "off",
    "react-doctor/no-transition-all": "off",
    "react-doctor/nextjs-no-img-element": "off",
    "react-doctor/jsx-no-constructed-context-values": "off",
    "react-doctor/control-has-associated-label": "off",
    "react-doctor/url-prefilled-privileged-action": "off",
    "unused-file": "off",
    "react-doctor/prefer-module-scope-pure-function": "off",
    "react-doctor/no-redundant-roles": "off",
    "react-doctor/no-outline-none": "off",
    "react-doctor/no-effect-chain": "off",
    "react-doctor/no-derived-state-effect": "off",
    "react-doctor/no-derived-state": "off",
    "react-doctor/nextjs-no-use-search-params-without-suspense": "off",
    "react-doctor/insecure-crypto-risk": "off",
    "react-doctor/exhaustive-deps": "off",
    "react-doctor/async-await-in-loop": "off",
    "jsx-a11y/click-events-have-key-events": "off",
    "jsx-a11y/control-has-associated-label": "off",
    "jsx-a11y/no-static-element-interactions": "off"
  }
};